import { TTitleEnToUa } from '../../../infrastructure/interface';

export enum ETransitionsTZPPlace {
  TRANSITION_FINISH_KM1_POLYMERIZATION = 'TRANSITION_FINISH_KM1_POLYMERIZATION',
  TRANSITION_SEND_TO_LABORATORY = 'TRANSITION_SEND_TO_LABORATORY',
}

export enum ETransitionsUK {
  TRANSITION_FINISH_KM1_POLYMERIZATION = 'lorem ipsum',
  TRANSITION_SEND_TO_LABORATORY = 'lorem ipsum',
}

export const chooseTransitionsUa: TTitleEnToUa = {
  [ETransitionsTZPPlace.TRANSITION_FINISH_KM1_POLYMERIZATION]: ETransitionsUK.TRANSITION_FINISH_KM1_POLYMERIZATION,
  [ETransitionsTZPPlace.TRANSITION_SEND_TO_LABORATORY]: ETransitionsUK.TRANSITION_SEND_TO_LABORATORY,
};

enum EStateUK {
  STATE_NEW = 'lorem ipsum',
  STATE_KM1_POLYMERIZATION_FINISHED = 'lorem ipsum',
  STATE_SENT_TO_LABORATORY = 'lorem ipsum',
  STATE_ANALYSIS_CREATED = 'lorem ipsum',
  STATE_ANALYSIS_DONE = 'lorem ipsum',
}

export enum EState {
  STATE_NEW = 'STATE_NEW',
  STATE_KM1_POLYMERIZATION_FINISHED = 'STATE_KM1_POLYMERIZATION_FINISHED',
  STATE_SENT_TO_LABORATORY = 'STATE_SENT_TO_LABORATORY',
  STATE_ANALYSIS_CREATED = 'STATE_ANALYSIS_CREATED',
  STATE_ANALYSIS_DONE = 'STATE_ANALYSIS_DONE',
}

export const chooseStateUa: TTitleEnToUa = {
  [EState.STATE_NEW]: EStateUK.STATE_NEW,
  [EState.STATE_KM1_POLYMERIZATION_FINISHED]: EStateUK.STATE_KM1_POLYMERIZATION_FINISHED,
  [EState.STATE_SENT_TO_LABORATORY]: EStateUK.STATE_SENT_TO_LABORATORY,
  [EState.STATE_ANALYSIS_CREATED]: EStateUK.STATE_ANALYSIS_CREATED,
  [EState.STATE_ANALYSIS_DONE]: EStateUK.STATE_ANALYSIS_DONE,
};

export const choiceColorState: TTitleEnToUa = {
  [EState.STATE_NEW]: 'rgb(27, 151, 245)', // (голубой)
  [EState.STATE_KM1_POLYMERIZATION_FINISHED]: 'rgb(126, 126, 126)', // (серый)
  [EState.STATE_SENT_TO_LABORATORY]: 'rgb(253, 201, 15)', // (желтый)
  [EState.STATE_ANALYSIS_CREATED]: 'rgb(253, 201, 15)', // (желтый)
  [EState.STATE_ANALYSIS_DONE]: 'rgb(57, 203, 127)', // (зеленый)
};
