export const ROCKET_ENGINE_COMMAND_NAMES: Record<string, string> = {
  ASSEMBLE_UNLOADED_ENGINE: 'TRANSITION_ASSEMBLE_UNLOADED_ENGINE',
  DETERMINE_CENTER_OF_GRAVITY_UNLOADED_ENGINE: 'TRANSITION_DETERMINE_CENTER_OF_GRAVITY_UNLOADED_ENGINE',
  RETURN_ALL_PRESSFORM_WITH_TZP_FROM_MEASUREMENTS: 'TRANSITION_RETURN_ALL_PRESSFORM_WITH_TZP_FROM_MEASUREMENTS ',
};
